### ISSUE TITLE
[WIP] 뉴스레터 구독페이지 오류

### ISSUE THREAD

**Issue by Hansanghyeon** [beeclover/articleT#72]
![20220119_아티클티 메인 개편 기획 V 02 001](https://user-images.githubusercontent.com/42893446/150976465-70ddf067-918a-4ef8-965d-1e2b17d8d1a5.jpeg)

- 내용 전달 받아야함

**Comment by Hansanghyeon** [comment]
클라이언트의 자료가 필요함

**Comment by Seunghan-Lee** [comment]
> 

확인해서 전달하겠음.
