### ISSUE TITLE
포스트 영역 (연관 포스트)

### ISSUE THREAD

**Issue by Hansanghyeon** [beeclover/articleT#73]
ppt 14

컬렉션을 태그로 변경된다.

기존 포스트 영역에 컬렉션 포스트 추천 영역을 제거

현재 포스트의 연관 태그

- 첫 번째 태그를 기준
  - 첫 번째 태그는 태그가 생성된 순서 기준
- 태그가 지정된 포스트 가져옴
- 최신순으로 보여줌

---

TODOs

- [x] 해쉬태그 섹션
- [x] 포스트 상세 디자인 바뀐부분
- [x] #95

---

연관이슈

- #87

**Comment by Hansanghyeon** [comment]
개발하면서 추가된 로직

태그가 지정된 포스트를 가져왔는데 5개 이하라면 해당 태그가 지정되지 않은 모든 포스트중 최신순으로 나머지 모자른 포스트 갯수를 가져오고 순서는
- 지정된 태그 포스트 최신순
- 태그가 지정되지 않은 모든 포스트의 최신순 모자른 갯수

**Comment by Seunghan-Lee** [comment]
@Hansanghyeon 그냥 포스트가 부족하면 부족한대로 놔둬야 할 듯. 그쪽에서 부족한 포스트를 채워줘야 할 것 같다.
