### ISSUE TITLE
기존 포스트의 링크타입 변경

### ISSUE THREAD

**Issue by Hansanghyeon** [beeclover/articleT#79]
js로 현재 모든 외부 링크를 새창으로 열리게 할 수 있습니다. 하지만 작성자가 새창으로 하고싶지 않다하여도 모두 새창으로 열리게 해야합니다. 이 의도가 맞다면 이렇게 진행하겠습니다.

**Comment by Seunghan-Lee** [comment]
@Hansanghyeon 다시 확인해보니 모든 링크를 새창으로 띄우는게 아니고 상단메뉴나 하단 메뉴 등 우리가 직접 삽입하는 링크들 중에 외부사이트로 이동하는것만 새창으로 띄워달라는 얘기네.
포스트 링크타입은 그대로 두면되고.
푸터등에 있는 여러 메뉴들중에 외부사이트로 이동하는 것만 모두 새창으로 띄우는걸로 변경해줘.

**Comment by Hansanghyeon** [comment]
최상단 우측 메뉴가 `target="_blank"` 속성 누락
개편된 디자인에서 우측 메뉴가 사라짐
