### ISSUE TITLE
Card 리디자인

### ISSUE THREAD

**Issue by Hansanghyeon** [beeclover/articleT#88]
- [ ] s1
- [x] s2
- [ ] s3
- [ ] s4
- [ ] s5
- [x] s6

https://wiki.beeclover.pro/share/102ae5e7-3167-44b3-a94a-974c5ae2d512

---

- [x] s7 추가

**Comment by Seunghan-Lee** [comment]
@Hansanghyeon 이 부분은 내가 확인해줘야 할 내용은 없는거지?

**Comment by Hansanghyeon** [comment]
더이상의 카드 디자인 개편 없음.
